#!/bin/bash

XPI=profiler.xpi

ANDROID_APP_ID=org.mozilla.fennec_${USER}

# List add-on files here
zip -r $XPI bootstrap.js \
            install.rdf \
            chrome.manifest \
            content \
            locale \
            README.md \
    -x *.DS_Store*

# Push the add-on to your device to test
adb push "$XPI" /sdcard/"$XPI" && \
adb shell am start -a android.intent.action.VIEW \
                   -c android.intent.category.DEFAULT \
                   -d file:///mnt/sdcard/"$XPI" \
                   -n $ANDROID_APP_ID/.App && \
echo Pushed $XPI to $ANDROID_APP_ID
