#!/usr/bin/env node

const fs = require('fs');
const child_process = require('child_process');
const os = require('os');
const dir = require('node-dir');
const { basename } = require('path');
const lodash = require('lodash');
const mkdirp = require('mkdirp');

const homedir = process.env['HOME'];
const ADDR2LINE = `${homedir}/.mozbuild/android-ndk-r11c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-addr2line`;

let NUM_ADDRESSES_PER_CHUNK = 1000;

async function readProfileStream(stream) {
	// JSON.parse just barfs
	return new Promise(resolve => {
		let bufs = [];
		stream.on('data', function(data) {
			bufs.push(data);
		});

		stream.on('close', function() {
			resolve(JSON.parse(Buffer.concat(bufs)));
		});

		stream.on('error', function(e) {
			console.error('Failed to parse profile: ' + e);
			resolve(null);
		});
	});
}

async function writeProfile(profilePath, profile) {
	return new Promise(resolve => {
		const ws = fs.createWriteStream(profilePath);
		ws.end(JSON.stringify(profile), resolve);
	});
}

function findLib(libs, offset) {
	for (let lib of libs) {
		if (offset >= lib.start && offset < lib.end) {
			return lib;
		}
	}

	return null;
}

async function buildLibCache(libdir, objdir) {
	let cache = {};

	const addPaths = function addPaths(paths) {
		for (let path of paths.files) {
			cache[basename(path)] = path;
		}
	}

	return new Promise(resolve => {
		dir.paths(objdir, (err, paths) => {
			addPaths(paths);
			dir.paths(libdir, (err, paths) => {
				addPaths(paths);
				resolve(cache);
			});
		});
	});
}

async function findLibPath(name) {
	if (!libCache) {
		libCache = await buildLibCache();
	}

	return libCache[name];
}

async function resolveSymbols(path, chunk) {
	const offsets = chunk.map(item => '0x' + item.offset.toString(16));
	return new Promise(resolve => {
		let args = ['-e', path, '-f', '-C'];
		args = args.concat(offsets);
		let proc = child_process.spawn(ADDR2LINE, args);
		
		let bufs = [];
		proc.stdout.on('data', data => {
			bufs.push(data);
		});

		proc.stdout.on('close', () => {
			let lines = Buffer.concat(bufs).toString().split('\n');
			for (let i = 0; i < chunk.length; i++) {
				const location = ('0x' + chunk[i].offset.toString(16) + ' in ' + chunk[i].libName);
				const sym = lines[i * 2];
				chunk[i].symbol = sym ? sym : location;
			}
			resolve(chunk);
		});
	});
}

async function symbolicateThread(libCache, libs, thread) {
	const strings = thread.stringTable;
	let libOffsets = {};

	if (!strings) {
		return Promise.resolve(thread);
	}

	for (let i = 0; i < strings.length; i++) {
		const sym = strings[i];
		if (sym.indexOf('0x') != 0) {
			continue;
		}

		const offset = parseInt(sym, 16);
		let lib = findLib(libs, offset);
		if (!lib) {
			continue;
		}

		if (!libOffsets[lib.name]) {
			libOffsets[lib.name] = [];
		}

		const adjOffset = ((offset - lib.start + lib.offset) & ~1) - 1

		libOffsets[lib.name].push({
			index: i,
			libName: lib.name,
			offset: offset - lib.start + lib.offset,
			symbol: null
		});
	}

	let promises = [];

	for (const name in libOffsets) {
		let chunks = lodash.chunk(libOffsets[name], NUM_ADDRESSES_PER_CHUNK);
		let libPath = libCache[name];

		promises.push(Promise.all(chunks.map(chunk => resolveSymbols(libPath, chunk))));
	}

	await Promise.all(promises);

	for (const name in libOffsets) {
		for (const item of libOffsets[name]) {
			strings[item.index] = item.symbol;
		}
	}
}

function getLibPath() {
	const serial = child_process.execSync('adb shell getprop ro.serialno');
	return `./remote-libs/${serial}`.trim();
}

async function main() {
	const profilePath = process.argv[2];
	if (!profilePath) {
		console.error('ERROR: pass as sampler profile path');
		process.exit(1);
	}

	const profile = await readProfile(profilePath);
	if (!profile) {
		console.error('ERROR: failed to read profile');
		process.exit(1);
	}

	const promises = profile.threads.map(thread => symbolicateThread(profile.libs, thread));
	await Promise.all(promises);

	const symProfilePath = profilePath + '.sym';
	await writeProfile(symProfilePath, profile);
	console.log('Wrote symbolicated profile to: ' + symProfilePath);
}

process.on('unhandledRejection', function(err) {
	console.error('ERROR: ', err);
});

require('yargs')
	.usage('$0 <cmd> [args]')
	.command('pull-libs', 'Pull libraries from connected device', function() {
		const libPath = getLibPath();
		mkdirp.sync(libPath);

		child_process.spawnSync('adb', ['pull', '/system/lib', libPath], {
			stdio: ['inherit', 'inherit', 'inherit']
		});
	})
	.command('pull-profile', 'Pull a profile from connected device', {
		objdir: {
			default: null,
			describe: 'Gecko object directory'
		},
		output: {
			default: 'gecko_profile_syms.json',
			describe: 'Output file name'
		}
	}, async function(argv) {
		if (!argv.objdir) {
			console.error('Must specify object directory via --objdir');
			process.exit(1);
		}

		const pullProcess = child_process.spawn('adb', ['shell', 'cat', '/sdcard/gecko_profile.json']);

		const profile = await readProfileStream(pullProcess.stdout);
		if (!profile) {
			console.error('ERROR: failed to read profile');
			process.exit(1);
		}

		const libCache = await buildLibCache(getLibPath(), argv.objdir);

		const promises = profile.threads.map(thread => symbolicateThread(libCache, profile.libs, thread));
		await Promise.all(promises);

		await writeProfile(argv.output, profile);
		console.log('Wrote symbolicated profile to: ' + argv.output);
	})
	.help()
	.argv;